import { describe, test, expect, vi, beforeEach, afterEach } from 'vitest';
import { ascendingOrderComparerFactory } from '../src/utils/ascendingOrderComparerFactory';

interface iDep {
  moduleName: string;
  version: string;
  dev?: boolean;
}

const dep: iDep = {
  moduleName: 'react',
  version: '17.0.2',
  dev: false,
};

const _arr: iDep[] = [
  { moduleName: '@types/react', version: '18.3.3.' },
  { moduleName: 'react', version: '18.2.0.' },
  { moduleName: '@types/', version: '18.3.3.' },
  { moduleName: 'loader-utils', version: '3.2.1' },
  { moduleName: 'react', version: '18.2.0' },
  { moduleName: 'react-dom', version: '18.2.0' },
  { moduleName: 'react-scripts', version: '5.0.1' },
  { moduleName: '@types/react', version: '18.0.25' },
  { moduleName: '@types/react-dom', version: '18.0.9' },
  { moduleName: 'typescript', version: '4.4.2' },
];

const _shouldBe: iDep[] = [
  { moduleName: '@types/', version: '18.3.3.' },
  { moduleName: '@types/react', version: '18.3.3.' },
  { moduleName: '@types/react', version: '18.0.25' },
  { moduleName: '@types/react-dom', version: '18.0.9' },
  { moduleName: 'loader-utils', version: '3.2.1' },
  { moduleName: 'react', version: '18.2.0.' },
  { moduleName: 'react', version: '18.2.0' },
  { moduleName: 'react-dom', version: '18.2.0' },
  { moduleName: 'react-scripts', version: '5.0.1' },
  { moduleName: 'typescript', version: '4.4.2' },
];

/***
 * `ascendingOrderComparerFactory()`はArray.prototype.sort関数のコールバック関数を生成するファクトリ関数である。
 * オブジェクト配列の要素であるオブジェクトの任意のプロパティをソートの基準として昇順に並び替えるコールバック関数を生成する
 *
 *
 * */
describe('Test ascendingOrderComparerFactory', () => {
  // 文字列で昇順に並び替える関数の生成
  test("Sort function generated by ascendingOrderComparerFactory('moduleName') must sort _arr with respect to the value of the “moduleName” property", () => {
    const comparer = ascendingOrderComparerFactory<iDep>('moduleName');
    expect(_arr.sort(comparer)).toEqual(_shouldBe);
  });
});
